### ISSUE TITLE
Sobre Solid

### ISSUE THREAD

**Issue by Alvatros96** [Arquisoft/viade_es1a#12]
Para que os registreis en Solid y tengais vuestro POD para hacer pruebas
https://solid.community/

Mi usuario es igual que el de mi github.

**Comment by samuelmorenov** [comment]
Yo cree mi cuenta el año pasado, os la dejo aquí por si quereis hacer pruebas de añadir amigos y esas cosas: https://samuelmorenov.solid.community/

**Comment by kevin23699** [comment]
Os dejo la mía también:
https://kevin23699.solid.community/

**Comment by Alvatros96** [comment]
La mia:
https://alvatros96.solid.community/

**Comment by samuelmorenov** [comment]
Tutorial rapido para hacer una app de SOLID:
https://solid.inrupt.com/docs/app-on-your-lunch-break
