### ISSUE TITLE
Empezar a aprender react

### ISSUE THREAD

**Issue by kevin23699** [Arquisoft/viade_es1a#7]
Os recomiendo este tutorial para ir empezando a aprender react:
https://www.codecademy.com/learn/react-101

**Comment by Alvatros96** [comment]
La verdad que me ha aclarado algunas cosas, gracias!

**Comment by kevin23699** [comment]
Aquí tenéis la segunda parte:
https://www.codecademy.com/learn/react-102

**Comment by Alvatros96** [comment]
Aqui para comenzar con JavaScript:
https://www.codecademy.com/learn/introduction-to-javascript

**Comment by kevin23699** [comment]
Solid explicado en 3 min:
https://www.youtube.com/watch?v=2GP7CcsKu8g

**Comment by kevin23699** [comment]
Otro tutorial de react:
https://es.reactjs.org/tutorial/tutorial.html

**Comment by samuelmorenov** [comment]
Curso en video para comenzar con react:
https://www.youtube.com/watch?v=vAvCcjSAGDY

**Comment by Alvatros96** [comment]
Exension para firefox de react:
https://addons.mozilla.org/es/firefox/addon/react-devtools/?src=search
